import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import BgFixed from "@/components/bgfixed";
//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body /* className={inter.className} */className="container mx-auto px-[15px] md:px-[50px]">
        <BgFixed/>
        <Header />
        <div className="relative">
          {children}
        </div>
        <Footer />
        </body>
    </html>
  );
}
