import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer";
import BgFixed from "@/components/bgFixed";


import CustomFont from 'next/font/local'

const Involve = CustomFont({
    src: "../public/fonts/Involve-Regular.ttf",
    variable: '--font-Involve'
  })

const DejaVu = CustomFont(
  {
    src: "../public/fonts//DejaVuSans-ExtraLight.ttf",
    variable: '--font-DejaVu'
  }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Involve.variable} ${DejaVu.variable} container mx-auto px-[15px] md:px-[50px]`}>
        <BgFixed/>
        <Header />
        <div className="relative">
          {children}
        </div>
        <Footer />
        </body>
    </html>
  );
}
